create table "public"."Allergens" (
    "id" bigint generated by default as identity not null,
    "allergen_name" text not null
);


alter table "public"."Allergens" enable row level security;

create table "public"."Allergens_to_Dishes" (
    "allergen_id" bigint generated by default as identity not null,
    "dish_id" bigint not null
);


alter table "public"."Allergens_to_Dishes" enable row level security;

create table "public"."Categories" (
    "id" bigint generated by default as identity not null,
    "category_name" text not null
);


alter table "public"."Categories" enable row level security;

create table "public"."Categories_to_Dishes" (
    "category_id" bigint not null,
    "dish_id" bigint not null
);


alter table "public"."Categories_to_Dishes" enable row level security;

create table "public"."Dish_Schedule" (
    "id" bigint not null,
    "date" date not null
);


alter table "public"."Dish_Schedule" enable row level security;

create table "public"."Dish_type" (
    "id" bigint generated by default as identity not null,
    "dish_type" text not null
);


alter table "public"."Dish_type" enable row level security;

create table "public"."Dishes" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "title" text not null,
    "description" text not null,
    "image" text,
    "dish_type" bigint,
    "calories" integer
);


alter table "public"."Dishes" enable row level security;

create table "public"."Serving_spots" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "description" text
);


alter table "public"."Serving_spots" enable row level security;

CREATE UNIQUE INDEX "Allergens_pkey" ON public."Allergens" USING btree (id);

CREATE UNIQUE INDEX "Allergens_to_Dishes_pkey" ON public."Allergens_to_Dishes" USING btree (allergen_id, dish_id);

CREATE UNIQUE INDEX "Categories_pkey" ON public."Categories" USING btree (id);

CREATE UNIQUE INDEX "Categories_to_Dishes_pkey" ON public."Categories_to_Dishes" USING btree (category_id, dish_id);

CREATE UNIQUE INDEX "Dish_Schedule_pkey" ON public."Dish_Schedule" USING btree (id, date);

CREATE UNIQUE INDEX "Dish_type_dish_type_key" ON public."Dish_type" USING btree (dish_type);

CREATE UNIQUE INDEX "Dish_type_pkey" ON public."Dish_type" USING btree (id);

CREATE UNIQUE INDEX "Dishes_pkey" ON public."Dishes" USING btree (id);

CREATE UNIQUE INDEX "Serving_spots_pkey" ON public."Serving_spots" USING btree (id);

alter table "public"."Allergens" add constraint "Allergens_pkey" PRIMARY KEY using index "Allergens_pkey";

alter table "public"."Allergens_to_Dishes" add constraint "Allergens_to_Dishes_pkey" PRIMARY KEY using index "Allergens_to_Dishes_pkey";

alter table "public"."Categories" add constraint "Categories_pkey" PRIMARY KEY using index "Categories_pkey";

alter table "public"."Categories_to_Dishes" add constraint "Categories_to_Dishes_pkey" PRIMARY KEY using index "Categories_to_Dishes_pkey";

alter table "public"."Dish_Schedule" add constraint "Dish_Schedule_pkey" PRIMARY KEY using index "Dish_Schedule_pkey";

alter table "public"."Dish_type" add constraint "Dish_type_pkey" PRIMARY KEY using index "Dish_type_pkey";

alter table "public"."Dishes" add constraint "Dishes_pkey" PRIMARY KEY using index "Dishes_pkey";

alter table "public"."Serving_spots" add constraint "Serving_spots_pkey" PRIMARY KEY using index "Serving_spots_pkey";

alter table "public"."Allergens_to_Dishes" add constraint "public_Allergens_to_Dishes_allergen_id_fkey" FOREIGN KEY (allergen_id) REFERENCES "Allergens"(id) not valid;

alter table "public"."Allergens_to_Dishes" validate constraint "public_Allergens_to_Dishes_allergen_id_fkey";

alter table "public"."Allergens_to_Dishes" add constraint "public_Allergens_to_Dishes_dish_id_fkey" FOREIGN KEY (dish_id) REFERENCES "Dishes"(id) not valid;

alter table "public"."Allergens_to_Dishes" validate constraint "public_Allergens_to_Dishes_dish_id_fkey";

alter table "public"."Categories_to_Dishes" add constraint "public_Categories_to_Dishes_category_id_fkey" FOREIGN KEY (category_id) REFERENCES "Categories"(id) not valid;

alter table "public"."Categories_to_Dishes" validate constraint "public_Categories_to_Dishes_category_id_fkey";

alter table "public"."Categories_to_Dishes" add constraint "public_Categories_to_Dishes_dish_id_fkey" FOREIGN KEY (dish_id) REFERENCES "Dishes"(id) not valid;

alter table "public"."Categories_to_Dishes" validate constraint "public_Categories_to_Dishes_dish_id_fkey";

alter table "public"."Dish_Schedule" add constraint "public_Dish_Schedule_id_fkey" FOREIGN KEY (id) REFERENCES "Dishes"(id) not valid;

alter table "public"."Dish_Schedule" validate constraint "public_Dish_Schedule_id_fkey";

alter table "public"."Dish_type" add constraint "Dish_type_dish_type_key" UNIQUE using index "Dish_type_dish_type_key";

alter table "public"."Dishes" add constraint "public_Dishes_dish_type_fkey" FOREIGN KEY (dish_type) REFERENCES "Dish_type"(id) not valid;

alter table "public"."Dishes" validate constraint "public_Dishes_dish_type_fkey";

grant delete on table "public"."Allergens" to "anon";

grant insert on table "public"."Allergens" to "anon";

grant references on table "public"."Allergens" to "anon";

grant select on table "public"."Allergens" to "anon";

grant trigger on table "public"."Allergens" to "anon";

grant truncate on table "public"."Allergens" to "anon";

grant update on table "public"."Allergens" to "anon";

grant delete on table "public"."Allergens" to "authenticated";

grant insert on table "public"."Allergens" to "authenticated";

grant references on table "public"."Allergens" to "authenticated";

grant select on table "public"."Allergens" to "authenticated";

grant trigger on table "public"."Allergens" to "authenticated";

grant truncate on table "public"."Allergens" to "authenticated";

grant update on table "public"."Allergens" to "authenticated";

grant delete on table "public"."Allergens" to "service_role";

grant insert on table "public"."Allergens" to "service_role";

grant references on table "public"."Allergens" to "service_role";

grant select on table "public"."Allergens" to "service_role";

grant trigger on table "public"."Allergens" to "service_role";

grant truncate on table "public"."Allergens" to "service_role";

grant update on table "public"."Allergens" to "service_role";

grant delete on table "public"."Allergens_to_Dishes" to "anon";

grant insert on table "public"."Allergens_to_Dishes" to "anon";

grant references on table "public"."Allergens_to_Dishes" to "anon";

grant select on table "public"."Allergens_to_Dishes" to "anon";

grant trigger on table "public"."Allergens_to_Dishes" to "anon";

grant truncate on table "public"."Allergens_to_Dishes" to "anon";

grant update on table "public"."Allergens_to_Dishes" to "anon";

grant delete on table "public"."Allergens_to_Dishes" to "authenticated";

grant insert on table "public"."Allergens_to_Dishes" to "authenticated";

grant references on table "public"."Allergens_to_Dishes" to "authenticated";

grant select on table "public"."Allergens_to_Dishes" to "authenticated";

grant trigger on table "public"."Allergens_to_Dishes" to "authenticated";

grant truncate on table "public"."Allergens_to_Dishes" to "authenticated";

grant update on table "public"."Allergens_to_Dishes" to "authenticated";

grant delete on table "public"."Allergens_to_Dishes" to "service_role";

grant insert on table "public"."Allergens_to_Dishes" to "service_role";

grant references on table "public"."Allergens_to_Dishes" to "service_role";

grant select on table "public"."Allergens_to_Dishes" to "service_role";

grant trigger on table "public"."Allergens_to_Dishes" to "service_role";

grant truncate on table "public"."Allergens_to_Dishes" to "service_role";

grant update on table "public"."Allergens_to_Dishes" to "service_role";

grant delete on table "public"."Categories" to "anon";

grant insert on table "public"."Categories" to "anon";

grant references on table "public"."Categories" to "anon";

grant select on table "public"."Categories" to "anon";

grant trigger on table "public"."Categories" to "anon";

grant truncate on table "public"."Categories" to "anon";

grant update on table "public"."Categories" to "anon";

grant delete on table "public"."Categories" to "authenticated";

grant insert on table "public"."Categories" to "authenticated";

grant references on table "public"."Categories" to "authenticated";

grant select on table "public"."Categories" to "authenticated";

grant trigger on table "public"."Categories" to "authenticated";

grant truncate on table "public"."Categories" to "authenticated";

grant update on table "public"."Categories" to "authenticated";

grant delete on table "public"."Categories" to "service_role";

grant insert on table "public"."Categories" to "service_role";

grant references on table "public"."Categories" to "service_role";

grant select on table "public"."Categories" to "service_role";

grant trigger on table "public"."Categories" to "service_role";

grant truncate on table "public"."Categories" to "service_role";

grant update on table "public"."Categories" to "service_role";

grant delete on table "public"."Categories_to_Dishes" to "anon";

grant insert on table "public"."Categories_to_Dishes" to "anon";

grant references on table "public"."Categories_to_Dishes" to "anon";

grant select on table "public"."Categories_to_Dishes" to "anon";

grant trigger on table "public"."Categories_to_Dishes" to "anon";

grant truncate on table "public"."Categories_to_Dishes" to "anon";

grant update on table "public"."Categories_to_Dishes" to "anon";

grant delete on table "public"."Categories_to_Dishes" to "authenticated";

grant insert on table "public"."Categories_to_Dishes" to "authenticated";

grant references on table "public"."Categories_to_Dishes" to "authenticated";

grant select on table "public"."Categories_to_Dishes" to "authenticated";

grant trigger on table "public"."Categories_to_Dishes" to "authenticated";

grant truncate on table "public"."Categories_to_Dishes" to "authenticated";

grant update on table "public"."Categories_to_Dishes" to "authenticated";

grant delete on table "public"."Categories_to_Dishes" to "service_role";

grant insert on table "public"."Categories_to_Dishes" to "service_role";

grant references on table "public"."Categories_to_Dishes" to "service_role";

grant select on table "public"."Categories_to_Dishes" to "service_role";

grant trigger on table "public"."Categories_to_Dishes" to "service_role";

grant truncate on table "public"."Categories_to_Dishes" to "service_role";

grant update on table "public"."Categories_to_Dishes" to "service_role";

grant delete on table "public"."Dish_Schedule" to "anon";

grant insert on table "public"."Dish_Schedule" to "anon";

grant references on table "public"."Dish_Schedule" to "anon";

grant select on table "public"."Dish_Schedule" to "anon";

grant trigger on table "public"."Dish_Schedule" to "anon";

grant truncate on table "public"."Dish_Schedule" to "anon";

grant update on table "public"."Dish_Schedule" to "anon";

grant delete on table "public"."Dish_Schedule" to "authenticated";

grant insert on table "public"."Dish_Schedule" to "authenticated";

grant references on table "public"."Dish_Schedule" to "authenticated";

grant select on table "public"."Dish_Schedule" to "authenticated";

grant trigger on table "public"."Dish_Schedule" to "authenticated";

grant truncate on table "public"."Dish_Schedule" to "authenticated";

grant update on table "public"."Dish_Schedule" to "authenticated";

grant delete on table "public"."Dish_Schedule" to "service_role";

grant insert on table "public"."Dish_Schedule" to "service_role";

grant references on table "public"."Dish_Schedule" to "service_role";

grant select on table "public"."Dish_Schedule" to "service_role";

grant trigger on table "public"."Dish_Schedule" to "service_role";

grant truncate on table "public"."Dish_Schedule" to "service_role";

grant update on table "public"."Dish_Schedule" to "service_role";

grant delete on table "public"."Dish_type" to "anon";

grant insert on table "public"."Dish_type" to "anon";

grant references on table "public"."Dish_type" to "anon";

grant select on table "public"."Dish_type" to "anon";

grant trigger on table "public"."Dish_type" to "anon";

grant truncate on table "public"."Dish_type" to "anon";

grant update on table "public"."Dish_type" to "anon";

grant delete on table "public"."Dish_type" to "authenticated";

grant insert on table "public"."Dish_type" to "authenticated";

grant references on table "public"."Dish_type" to "authenticated";

grant select on table "public"."Dish_type" to "authenticated";

grant trigger on table "public"."Dish_type" to "authenticated";

grant truncate on table "public"."Dish_type" to "authenticated";

grant update on table "public"."Dish_type" to "authenticated";

grant delete on table "public"."Dish_type" to "service_role";

grant insert on table "public"."Dish_type" to "service_role";

grant references on table "public"."Dish_type" to "service_role";

grant select on table "public"."Dish_type" to "service_role";

grant trigger on table "public"."Dish_type" to "service_role";

grant truncate on table "public"."Dish_type" to "service_role";

grant update on table "public"."Dish_type" to "service_role";

grant delete on table "public"."Dishes" to "anon";

grant insert on table "public"."Dishes" to "anon";

grant references on table "public"."Dishes" to "anon";

grant select on table "public"."Dishes" to "anon";

grant trigger on table "public"."Dishes" to "anon";

grant truncate on table "public"."Dishes" to "anon";

grant update on table "public"."Dishes" to "anon";

grant delete on table "public"."Dishes" to "authenticated";

grant insert on table "public"."Dishes" to "authenticated";

grant references on table "public"."Dishes" to "authenticated";

grant select on table "public"."Dishes" to "authenticated";

grant trigger on table "public"."Dishes" to "authenticated";

grant truncate on table "public"."Dishes" to "authenticated";

grant update on table "public"."Dishes" to "authenticated";

grant delete on table "public"."Dishes" to "service_role";

grant insert on table "public"."Dishes" to "service_role";

grant references on table "public"."Dishes" to "service_role";

grant select on table "public"."Dishes" to "service_role";

grant trigger on table "public"."Dishes" to "service_role";

grant truncate on table "public"."Dishes" to "service_role";

grant update on table "public"."Dishes" to "service_role";

grant delete on table "public"."Serving_spots" to "anon";

grant insert on table "public"."Serving_spots" to "anon";

grant references on table "public"."Serving_spots" to "anon";

grant select on table "public"."Serving_spots" to "anon";

grant trigger on table "public"."Serving_spots" to "anon";

grant truncate on table "public"."Serving_spots" to "anon";

grant update on table "public"."Serving_spots" to "anon";

grant delete on table "public"."Serving_spots" to "authenticated";

grant insert on table "public"."Serving_spots" to "authenticated";

grant references on table "public"."Serving_spots" to "authenticated";

grant select on table "public"."Serving_spots" to "authenticated";

grant trigger on table "public"."Serving_spots" to "authenticated";

grant truncate on table "public"."Serving_spots" to "authenticated";

grant update on table "public"."Serving_spots" to "authenticated";

grant delete on table "public"."Serving_spots" to "service_role";

grant insert on table "public"."Serving_spots" to "service_role";

grant references on table "public"."Serving_spots" to "service_role";

grant select on table "public"."Serving_spots" to "service_role";

grant trigger on table "public"."Serving_spots" to "service_role";

grant truncate on table "public"."Serving_spots" to "service_role";

grant update on table "public"."Serving_spots" to "service_role";

-- POLICIES

-- Allergens
create policy "Enable insert for authenticated users only" on "public"."Allergens" as permissive for insert to authenticated with check (true);
create policy "Enable read access for all users" on "public"."Allergens" as permissive for select to public using (true);

-- Allergens_to_Dishes
create policy "Enable insert for authenticated users only" on "public"."Allergens_to_Dishes" as permissive for insert to authenticated with check (true);
create policy "Enable read access for all users" on "public"."Allergens_to_Dishes" as permissive for select to public using (true);

-- Categories
create policy "Enable insert for authenticated users only" on "public"."Categories" as permissive for insert to authenticated with check (true);
create policy "Enable read access for all users" on "public"."Categories" as permissive for select to public using (true);

-- Categoreis_to_dishes
create policy "Enable insert for authenticated users only" on "public"."Categories_to_Dishes" as permissive for insert to authenticated with check (true);
create policy "Enable read access for all users" on "public"."Categories_to_Dishes" as permissive for select to public using (true);

-- Dish_schedule
create policy "Enable insert for authenticated anon only" on "public"."Dish_Schedule" as permissive for insert to authenticated with check (true);
create policy "Enable read access for all users" on "public"."Dish_Schedule" as permissive for select to public using (true);

-- Dish_type
create policy "Enable read access for all users" on "public"."Dish_type" as permissive for select to public using (true);

-- Dishes
create policy "Enable insert for anon users" on "public"."Dishes" as permissive for insert to authenticated with check (true);
create policy "Enable read access for all users" on "public"."Dishes" as permissive for select to public using (true);

-- Bucket
